language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.6"
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
# command to install dependencies
install:
  - sed -i '/django==/d' ./test_requirements.txt
  - sed -i '/django-reversion/d' ./test_requirements.txt
  - pip install -q -r test_requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip freeze
# command to run tests
script:
    - python runtests.py
    - flake8 .
    - mypy .
